server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

assets:
  overrides:
    /episodes: src/main/resources/episodes/

database:
  driverClass: com.mysql.jdbc.Driver
  user: crowdcast
  password: mlh
  url: jdbc:mysql://localhost:3306/crowdcast
  properties:
      charSet: UTF-8
      maxWaitForConnection: 1s
      minSize: 8
      maxSize: 32
      checkConnectionWhileIdle: false
      checkConnectionHealthWhenIdleFor: 10s
      closeConnectionIfIdleFor: 1 minute
      hibernate.hbm2ddl.auto: create
      currentSessionContextClass: thread